services:
  db:
    image: mysql:latest
    container_name: obralog
    restart: always
    networks:
      - network-obralog
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    networks:
      - network-obralog
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${PMA_PORT}:80'

networks:
  network-obralog:

volumes:
  db_data:
